#!/bin/sh
set -euxo pipefail

echo "===== EAS Pre-Build Hook ====="
echo "Current directory: $(pwd)"
echo "Node version: $(node --version)"
echo "NPM version: $(npm --version)"

echo "===== Building Vue app ====="
npm run build

echo "===== Checking Android directory ====="
if [ ! -d android ]; then
  echo "Android directory not found, adding it..."
  npx cap add android --skip-deps
else
  echo "Android directory exists"
fi

echo "===== Syncing Capacitor ====="
npx cap sync android

echo "===== Patching capacitor.build.gradle ====="
# Make the cordova.variables.gradle include conditional to prevent build failures
if [ -f "android/app/capacitor.build.gradle" ]; then
  # Check if the file already has the conditional check
  if ! grep -q "cordovaVariablesFile.exists()" android/app/capacitor.build.gradle; then
    echo "Adding conditional check for cordova.variables.gradle..."
    # Replace the unconditional apply with a conditional one
    sed -i.bak 's|apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"|def cordovaVariablesFile = file("../capacitor-cordova-android-plugins/cordova.variables.gradle")\nif (cordovaVariablesFile.exists()) {\n    apply from: cordovaVariablesFile\n}|' android/app/capacitor.build.gradle
    echo "✓ Patched capacitor.build.gradle"
  else
    echo "✓ capacitor.build.gradle already has conditional check"
  fi
fi

echo "===== Verifying generated files ====="
if [ -d "android/capacitor-cordova-android-plugins" ]; then
  echo "✓ capacitor-cordova-android-plugins directory exists"
  ls -la android/capacitor-cordova-android-plugins/

  if [ -f "android/capacitor-cordova-android-plugins/cordova.variables.gradle" ]; then
    echo "✓ cordova.variables.gradle exists"
    echo "Content:"
    cat android/capacitor-cordova-android-plugins/cordova.variables.gradle
  else
    echo "✗ cordova.variables.gradle NOT FOUND"
    echo "Creating it manually..."
    mkdir -p android/capacitor-cordova-android-plugins
    cat > android/capacitor-cordova-android-plugins/cordova.variables.gradle << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
ext {
  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
  // Plugin gradle extensions can append to this to have code run at the end.
  cdvPluginPostBuildExtras = []
  cordovaConfig = [:]
}
EOF
    echo "✓ Created cordova.variables.gradle manually"
  fi
else
  echo "✗ capacitor-cordova-android-plugins directory NOT FOUND"
  echo "Creating it manually..."
  mkdir -p android/capacitor-cordova-android-plugins
  cat > android/capacitor-cordova-android-plugins/cordova.variables.gradle << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
ext {
  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
  // Plugin gradle extensions can append to this to have code run at the end.
  cdvPluginPostBuildExtras = []
  cordovaConfig = [:]
}
EOF
  echo "✓ Created directory and cordova.variables.gradle manually"
fi

echo "===== Pre-build hook complete ====="
